# Generated by Django 2.2 on 2020-04-26 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Customer')),
                ('userCreator', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userModifier', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Header',
                'verbose_name_plural': 'Billings Header',
            },
        ),
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.BillingHeader')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Product')),
                ('userCreator', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userModifier', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Detail',
                'verbose_name_plural': 'Billings Details',
            },
        ),
    ]
