# Generated by Django 2.2 on 2020-05-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_billingdetail_billingheader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingdetail',
            options={'permissions': [('cashier_supervisor_billingdetail', 'Cashier Supervisor Permissions')], 'verbose_name': 'Billing Detail', 'verbose_name_plural': 'Billings Details'},
        ),
        migrations.AlterModelOptions(
            name='billingheader',
            options={'permissions': [('cashier_supervisor_billingheader', 'Cashier Supervisor Permissions')], 'verbose_name': 'Billing Header', 'verbose_name_plural': 'Billings Header'},
        ),
    ]
