# Generated by Django 2.2 on 2020-03-29 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0005_product'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'Suppliers'},
        ),
        migrations.CreateModel(
            name='AcquisitionHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('userModifier', models.IntegerField(blank=True, null=True)),
                ('aquisitionDate', models.DateField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('billNumber', models.CharField(max_length=100)),
                ('billDate', models.DateField()),
                ('subtotal', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Supplier')),
                ('userCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acquisition Header',
                'verbose_name_plural': 'Acquisitions Header',
            },
        ),
        migrations.CreateModel(
            name='AcquisitionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('userModifier', models.IntegerField(blank=True, null=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('supplierPrice', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('aquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.AcquisitionHeader')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Product')),
                ('userCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acquisition Header',
                'verbose_name_plural': 'Acquisitions Header',
            },
        ),
    ]
