# Generated by Django 2.2 on 2020-03-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20200329_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisitiondetail',
            options={},
        ),
    ]
