# Generated by Django 2.2 on 2020-03-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20200329_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisitiondetail',
            options={'verbose_name': 'Acquisition Header', 'verbose_name_plural': 'Acquisitions Header'},
        ),
    ]
