# Generated by Django 2.2 on 2020-03-29 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20200329_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisitiondetail',
            old_name='aquisition',
            new_name='acquisition',
        ),
        migrations.RenameField(
            model_name='acquisitionheader',
            old_name='aquisitionDate',
            new_name='acquisitionDate',
        ),
    ]
